//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystem.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManegementSystemDbEntities : DbContext
    {
        public ManegementSystemDbEntities()
            : base("name=ManegementSystemDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Egitmenler> Egitmenler { get; set; }
        public virtual DbSet<EgitmenMaas> EgitmenMaas { get; set; }
        public virtual DbSet<Odemeler> Odemeler { get; set; }
        public virtual DbSet<Plan_Tur> Plan_Tur { get; set; }
        public virtual DbSet<Uyeler> Uyeler { get; set; }
        public virtual DbSet<UyeOlcumleri> UyeOlcumleri { get; set; }
        public virtual DbSet<Yoneticiler> Yoneticiler { get; set; }
    }
}
