//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystem.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egitmenler
    {
        public int egitmen_id { get; set; }
        public string egitmen_AD { get; set; }
        public string egitmen_Soyad { get; set; }
        public string egitmen_DTarih { get; set; }
        public string egitmen_Cinsiyet { get; set; }
        public string egitmen_TLno { get; set; }
        public string egitmen_Mail { get; set; }
        public string egitmen_KTarih { get; set; }
        public string egitmen_Plan { get; set; }
        public string egitmen_Maas { get; set; }
    }
}
