//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystem.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EgitmenMaas
    {
        public int egitmen_id { get; set; }
        public string egitmen_Maas { get; set; }
    }
}
