//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystem.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odemeler
    {
        public int uye_id { get; set; }
        public string uye_Ad { get; set; }
        public string tutar { get; set; }
        public Nullable<int> plan_id { get; set; }
        public string plan_tutar { get; set; }
        public string yapılan_odeme { get; set; }
    }
}
