//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystem.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeOlcumleri
    {
        public int uye_id { get; set; }
        public string uye_Ad { get; set; }
        public string uye_boy { get; set; }
        public string uye_kilo { get; set; }
        public string uye_vy_oranı { get; set; }
        public string uye_kas_oranı { get; set; }
    }
}
