//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystem.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yoneticiler
    {
        public int yonetici_id { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string yonetici_AD { get; set; }
        public string yonetici_Soyad { get; set; }
        public string yonetici_Mail { get; set; }
    }
}
